name: Publish

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run build
      run: yarn build

    - name: Run export
      run: yarn export

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: ./dist

  deploy:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
        path: ./dist

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: portfolio.amon.house
